### ISSUE TITLE
Camel Case converter splits multi-digit numbers. 

### ISSUE THREAD

**Issue by marcusball** [nabil1337/case-helper#3]
When converting from camelCase, a string like `test123` will be converted into `test_1_2_3` if using snake case for example. 

It appears all of the tests for other cases appear to include tests with multi-digit numbers in which they are not separated. However, the camel case test only includes one assertion for mutliple digits: 

```
'iHaveNoIdeaWhatImDoing12' => 'I-Have-No-Idea-What-Im-Doing-1-2',
```

Is this the preferred functionality? 

I can see this project hasn't been updated in more than a year, but if you'll accept a pull request, I'm prepared to make changes to that it would convert it to `test_123`, or `404NotFound` to `404_not_found` rather than `4_0_4_not_found`.

**Comment by nabil1337** [comment]
Hi!

Thanks for pointing that out.
I'll gladly take a PR if it has/adjusts tests and adheres to the coding standard.
Lack of activity is just due to no open issues or pull requests.
